// <auto-generated />
using System;
using DanceStudio.Catalog.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DanceStudio.Catalog.DAL.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20251129204203_InitialCatalogCreate")]
    partial class InitialCatalogCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DanceStudio.Catalog.Domain.Entities.ClassInstructor", b =>
                {
                    b.Property<long>("DanceClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("danceclassid");

                    b.Property<long>("InstructorId")
                        .HasColumnType("bigint")
                        .HasColumnName("instructorid");

                    b.HasKey("DanceClassId", "InstructorId");

                    b.HasIndex("InstructorId");

                    b.ToTable("class_instructors", (string)null);
                });

            modelBuilder.Entity("DanceStudio.Catalog.Domain.Entities.DanceClass", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("defaultprice");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("difficultylevel");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dance_classes", (string)null);
                });

            modelBuilder.Entity("DanceStudio.Catalog.Domain.Entities.DanceClassDetail", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Requirements")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("requirements");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("videourl");

                    b.HasKey("Id");

                    b.ToTable("dance_class_details", (string)null);
                });

            modelBuilder.Entity("DanceStudio.Catalog.Domain.Entities.Instructor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firstname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastname");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("instructors", (string)null);
                });

            modelBuilder.Entity("DanceStudio.Catalog.Domain.Entities.ClassInstructor", b =>
                {
                    b.HasOne("DanceStudio.Catalog.Domain.Entities.DanceClass", "DanceClass")
                        .WithMany("ClassInstructors")
                        .HasForeignKey("DanceClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DanceStudio.Catalog.Domain.Entities.Instructor", "Instructor")
                        .WithMany("ClassInstructors")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanceClass");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("DanceStudio.Catalog.Domain.Entities.DanceClassDetail", b =>
                {
                    b.HasOne("DanceStudio.Catalog.Domain.Entities.DanceClass", "DanceClass")
                        .WithOne("Details")
                        .HasForeignKey("DanceStudio.Catalog.Domain.Entities.DanceClassDetail", "Id");

                    b.Navigation("DanceClass");
                });

            modelBuilder.Entity("DanceStudio.Catalog.Domain.Entities.DanceClass", b =>
                {
                    b.Navigation("ClassInstructors");

                    b.Navigation("Details");
                });

            modelBuilder.Entity("DanceStudio.Catalog.Domain.Entities.Instructor", b =>
                {
                    b.Navigation("ClassInstructors");
                });
#pragma warning restore 612, 618
        }
    }
}
